catalogMode: prefer
ignoreWorkspaceRootCheck: true
shamefullyHoist: true
shellEmulator: true
trustPolicy: no-downgrade

catalogs:
  dev:
    '@eslint/config-inspector': ^1.4.2
    '@types/node': ^24.10.9
    bumpp: ^10.4.0
    chokidar: ^5.0.0
    eslint-flat-config-utils: ^2.1.4
    eslint-plugin-astro: ^1.5.0
    eslint-plugin-format: ^1.3.1
    eslint-plugin-vue: ^10.7.0
    eslint-plugin-vuejs-accessibility: ^2.4.1
    eslint-typegen: ^2.3.0
    execa: ^9.6.1
    tinyglobby: ^0.2.15
    tsdown: ^0.19.0
    tsx: ^4.21.0
    typescript: ^5.9.3
    vitest: ^4.0.17
    vue: ^3.5.26
  peer:
    eslint: ^9.39.2
    eslint-plugin-astro-explicit-wrapper: ^1.0.5
  prod:
    '@antfu/eslint-config': ~7.0.0
    '@typescript-eslint/parser': ^8.53.0
    eslint-plugin-antfu: ^3.1.3
    local-pkg: ^1.1.2

onlyBuiltDependencies:
  - esbuild
