ignoreWorkspaceRootCheck: true
strictPeerDependencies: false
shamefullyHoist: true
shellEmulator: true
trustPolicy: no-downgrade

update:
  ignoreDeps:
    - typescript@7

overrides:
  '@typescript-eslint/eslint-plugin': 8.68.0
  '@typescript-eslint/parser': 8.68.0
  '@typescript-eslint/project-service': 8.68.0
  '@typescript-eslint/rule-tester': 8.68.0
  '@typescript-eslint/scope-manager': 8.68.0
  '@typescript-eslint/tsconfig-utils': 8.68.0
  '@typescript-eslint/type-utils': 8.68.0
  '@typescript-eslint/types': 8.68.0
  '@typescript-eslint/typescript-estree': 8.68.0
  '@typescript-eslint/utils': 8.68.0
  '@typescript-eslint/visitor-keys': 8.68.0

catalogs:
  dev:
    '@eslint/config-inspector': ^3.3.0
    '@types/node': ^26.4.0
    actionspack: ^0.1.5
    bumpp: ^12.2.2
    eslint-plugin-astro: ^2.1.1
    eslint-plugin-erasable-syntax-only: ^0.4.2
    eslint-plugin-format: ^2.0.1
    eslint-plugin-vuejs-accessibility: ^2.6.0
    eslint-typegen: ^2.3.1
    tinyexec: ^1.3.0
    tinyglobby: ^0.2.17
    tsdown: ^0.22.14
    tsdown-stale-guard: ^0.1.3
    tsnapi: ^1.4.2
    tsx: ^4.23.13
    typescript: ^6.0.3
    vitest: ^4.1.11
    vue: ^3.5.42
  peer:
    eslint: ^10.9.1
    eslint-plugin-astro-explicit-wrapper: ^1.0.5
  prod:
    '@antfu/eslint-config': ~9.3.0
    '@typescript-eslint/parser': ^8.68.0
    eslint-flat-config-utils: ^3.2.0
    eslint-plugin-antfu: ^3.2.3
    eslint-plugin-vue: ^10.10.0
    local-pkg: ^1.2.1

allowBuilds:
  esbuild: true
