catalogMode: prefer
ignoreWorkspaceRootCheck: true
shamefullyHoist: true
shellEmulator: true
trustPolicy: no-downgrade

overrides:
  '@typescript-eslint/eslint-plugin': 8.62.0
  '@typescript-eslint/parser': 8.62.0
  '@typescript-eslint/project-service': 8.62.0
  '@typescript-eslint/rule-tester': 8.62.0
  '@typescript-eslint/scope-manager': 8.62.0
  '@typescript-eslint/tsconfig-utils': 8.62.0
  '@typescript-eslint/type-utils': 8.62.0
  '@typescript-eslint/types': 8.62.0
  '@typescript-eslint/typescript-estree': 8.62.0
  '@typescript-eslint/utils': 8.62.0
  '@typescript-eslint/visitor-keys': 8.62.0
  eslint-plugin-astro: 2.1.1

catalogs:
  dev:
    '@eslint/config-inspector': ^3.0.4
    '@types/node': ^24.13.2
    bumpp: ^11.1.0
    eslint-plugin-astro: ^2.1.1
    eslint-plugin-format: ^2.0.1
    eslint-plugin-vuejs-accessibility: ^2.5.0
    eslint-typegen: ^2.3.1
    execa: ^9.6.1
    tinyglobby: ^0.2.17
    tsdown: ^0.22.3
    tsdown-stale-guard: ^0.1.2
    tsnapi: ^0.3.3
    tsx: ^4.22.4
    typescript: ^6.0.3
    vitest: ^4.1.9
    vue: ^3.5.38
  peer:
    eslint: ^10.5.0
    eslint-plugin-astro-explicit-wrapper: ^1.0.5
  prod:
    '@antfu/eslint-config': ~9.1.0
    '@typescript-eslint/parser': ^8.62.0
    eslint-flat-config-utils: ^3.2.0
    eslint-plugin-antfu: ^3.2.3
    eslint-plugin-vue: ^10.9.2
    local-pkg: ^1.2.1

allowBuilds:
  esbuild: true
