/**
 * Generated by tsnapi — public API snapshot of `@ycs77/eslint-config`
 */
// #region Functions
export declare function astro(_?: OptionsAstro & OptionsFiles & OptionsStylistic): Promise<TypedFlatConfigItem$1[]>;
export declare function imports(): Promise<TypedFlatConfigItem$1[]>;
export declare function javascript(): Promise<TypedFlatConfigItem$1[]>;
export declare function markdown(_?: OptionsStylistic): Promise<TypedFlatConfigItem$1[]>;
export declare function node(): Promise<TypedFlatConfigItem$1[]>;
export declare function stylistic(): Promise<TypedFlatConfigItem$1[]>;
export declare function test(): Promise<TypedFlatConfigItem$1[]>;
export declare function typescript(_?: OptionsComponentExts & OptionsFiles): Promise<TypedFlatConfigItem$1[]>;
export declare function vue(_?: OptionsHasTypeScript & OptionsStylistic & OptionsFiles): Promise<TypedFlatConfigItem$1[]>;
export declare function ycs77(_?: OptionsConfig$1 & Omit<TypedFlatConfigItem$1, 'files' | 'ignores'>, ..._: Awaitable<TypedFlatConfigItem$1 | TypedFlatConfigItem$1[] | FlatConfigComposer<any, any> | Linter.Config[]>[]): FlatConfigComposer<TypedFlatConfigItem$1, ConfigNames$1>;
// #endregion

// #region Variables
export declare const GLOB_ASTRO_JS: string;
export declare const GLOB_YAML_IN_MARKDOWN: string;
// #endregion

// #region Default Export
declare function _default(_?: OptionsConfig$1 & Omit<TypedFlatConfigItem$1, 'files' | 'ignores'>, ..._: Awaitable<TypedFlatConfigItem$1 | TypedFlatConfigItem$1[] | FlatConfigComposer<any, any> | Linter.Config[]>[]): FlatConfigComposer<TypedFlatConfigItem$1, ConfigNames$1>;
export default _default
// #endregion

// #region Other
export { GLOB_ALL_SRC }
export { GLOB_ASTRO }
export { GLOB_ASTRO_TS }
export { GLOB_CSS }
export { GLOB_EXCLUDE }
export { GLOB_GRAPHQL }
export { GLOB_HTML }
export { GLOB_JS }
export { GLOB_JSON }
export { GLOB_JSON5 }
export { GLOB_JSONC }
export { GLOB_JSX }
export { GLOB_LESS }
export { GLOB_MARKDOWN }
export { GLOB_MARKDOWN_CODE }
export { GLOB_MARKDOWN_IN_MARKDOWN }
export { GLOB_POSTCSS }
export { GLOB_SCSS }
export { GLOB_SRC }
export { GLOB_SRC_EXT }
export { GLOB_STYLE }
export { GLOB_SVELTE }
export { GLOB_SVG }
export { GLOB_TESTS }
export { GLOB_TOML }
export { GLOB_TS }
export { GLOB_TSX }
export { GLOB_VUE }
export { GLOB_XML }
export { GLOB_YAML }
// #endregion