export { GLOB_SRC_EXT, GLOB_SRC, GLOB_JS, GLOB_JSX, GLOB_TS, GLOB_TSX, GLOB_STYLE, GLOB_CSS, GLOB_POSTCSS, GLOB_LESS, GLOB_SCSS, GLOB_JSON, GLOB_JSON5, GLOB_JSONC, GLOB_MARKDOWN, GLOB_MARKDOWN_IN_MARKDOWN, GLOB_SVELTE, GLOB_VUE, GLOB_YAML, GLOB_TOML, GLOB_XML, GLOB_SVG, GLOB_HTML, GLOB_ASTRO, GLOB_ASTRO_TS, GLOB_GRAPHQL, GLOB_MARKDOWN_CODE, GLOB_TESTS, GLOB_ALL_SRC, GLOB_EXCLUDE } from '@antfu/eslint-config'

export const GLOB_YAML_IN_MARKDOWN = '**/*.md/**/*.y?(a)ml'
